---
name: build binaries
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_binaries:
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        os:
          - linux
          - windows
          - darwin
        arch:
          - amd64
          - arm64
    steps:
      - name: Set Env
        run: echo "BUILD_TIME=$(date -u '+%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Build the binaries
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build \
            -o toonamiaftermath-cli_${{ github.ref_name }}_${{ matrix.os }}_${{ matrix.arch }} \
            -ldflags=" \
              -X 'main.Version=${{ github.ref_name }}' \
              -X 'main.BuildTimestamp=${{ env.BUILD_TIME }}' \
              -X 'main.CommitHash=${{ github.sha }}' \
              -X 'main.Branch=${{ github.ref_name }}' \
            "
      - name: Cache Binary
        uses: actions/cache@v4
        with:
          path: ./toonamiaftermath-cli_${{ github.ref_name }}_${{ matrix.os }}_${{ matrix.arch }}
          key: toonamiaftermath-cli_${{ github.ref_name }}_${{ matrix.os }}_${{ matrix.arch }}
